/* One-off / regenerable: downloads the Google Fonts the app actually uses and
   writes them to public/fonts/ as plain files, plus a local fonts.css.
   Self-hosting removes the only external request the app makes, so typography
   survives offline and text never flashes in a fallback face. */
import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700' +
  '&family=Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700' +
  '&family=IBM+Plex+Mono:wght@500;600&display=swap';
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);
const OUT_DIR = path.resolve('public/fonts');

const slug = (value) => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const response = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
if (!response.ok) throw new Error(`Google Fonts responded ${response.status}`);
const css = await response.text();

const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[\s\S]*?\})/g)]
  .filter((match) => KEEP_SUBSETS.has(match[1]))
  .map((match) => ({ subset: match[1], face: match[2] }));

if (!blocks.length) throw new Error('no font-face blocks found — Google changed the CSS format');

mkdirSync(OUT_DIR, { recursive: true });

const byUrl = new Map();
let bytes = 0;

for (const block of blocks) {
  const family = /font-family:\s*'([^']+)'/.exec(block.face)?.[1];
  const url = /url\((https:[^)]+)\)/.exec(block.face)?.[1];
  if (!family || !url) throw new Error('could not parse a font-face block');

  if (!byUrl.has(url)) {
    // One variable file can back several weights, so name it after the source
    // URL rather than any single weight that happens to reference it.
    const hash = createHash('sha1').update(url).digest('hex').slice(0, 8);
    const file = `${slug(family)}-${block.subset}-${hash}.woff2`;
    const binary = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!binary.ok) throw new Error(`${url} responded ${binary.status}`);
    const buffer = Buffer.from(await binary.arrayBuffer());
    writeFileSync(path.join(OUT_DIR, file), buffer);
    bytes += buffer.length;
    byUrl.set(url, file);
  }

  block.face = block.face.replace(url, `/fonts/${byUrl.get(url)}`);
}

const header = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n`;
writeFileSync(path.join(OUT_DIR, 'fonts.css'), header + blocks.map((b) => b.face).join('\n\n') + '\n', 'utf8');

console.log(`${byUrl.size} files, ${(bytes / 1024).toFixed(0)} kB written to public/fonts/`);
