/* Staging step for receipt scanning: Tesseract normally pulls its worker, WASM
   core and language data from jsdelivr at runtime. That is the one request this
   app cannot afford — a delivery driver scanning a receipt in a loading bay with
   no signal would get nothing.

   So the files are copied into public/vendor/tesseract/<version>/ at build time
   and served from our own origin. The directory is versioned because these paths
   are cached immutably: bumping the folder is how a new core gets picked up.

   The core and worker come from node_modules (npm install already fetched them);
   only the ~4 MB language model is downloaded. Runs before dev and build. */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const tesseractPkg = JSON.parse(readFileSync('node_modules/tesseract.js/package.json', 'utf8'));
const corePkg = JSON.parse(readFileSync('node_modules/tesseract.js-core/package.json', 'utf8'));

// Folder name = the tesseract.js version the assets were staged for. Keeping it
// equal to the dependency version means "npm install a new tesseract.js" is
// enough to bust every immutable cache downstream.
const VERSION = tesseractPkg.version;
const OUT_DIR = path.resolve('public/vendor/tesseract', VERSION);

// Only LSTM cores. The app never asks tesseract for the legacy OEM, and the full
// cores are another ~7 MB of download for data nothing reads.
const CORES = ['tesseract-core-simd-lstm.wasm.js', 'tesseract-core-lstm.wasm.js'];
const WORKER = 'tesseract.js/dist/worker.min.js';

// Same source tesseract.js falls back to when no langPath is given, so the
// language model is byte-identical to the CDN one.
const LANG = 'eng';
const LANG_URL = `https://cdn.jsdelivr.net/npm/@tesseract.js-data/${LANG}/4.0.0_best_int/${LANG}.traineddata.gz`;
const LANG_FILE = `${LANG}.traineddata.gz`;

/** A file is only re-fetched when its size changes; equal size means same bytes. */
const sizeOf = (file) => (existsSync(file) ? readFileSync(file).length : -1);

let bytes = 0;
let copied = 0;

mkdirSync(OUT_DIR, { recursive: true });

const stage = (from, name) => {
  const to = path.join(OUT_DIR, name);
  const source = path.resolve('node_modules', from);
  if (!existsSync(source)) throw new Error(`missing ${from} — run npm install first`);
  if (sizeOf(to) !== sizeOf(source)) {
    copyFileSync(source, to);
    copied++;
  }
  bytes += sizeOf(to);
  return to;
};

stage(WORKER, 'worker.min.js');
for (const core of CORES) stage(`tesseract.js-core/${core}`, core);

// tesseract.js writes the traineddata into its virtual FS itself after gunzipping,
// but caching the raw .gz keeps the offline path free of any decompression cost
// on repeat scans.
const langTarget = path.join(OUT_DIR, LANG_FILE);
if (!existsSync(langTarget) || sizeOf(langTarget) < 100_000) {
  process.stdout.write(`   [ocr] downloading ${LANG_FILE} … `);
  const response = await fetch(LANG_URL);
  if (!response.ok) throw new Error(`${LANG_URL} responded ${response.status}`);
  const buffer = Buffer.from(await response.arrayBuffer());
  // A CDN error page is ~1 kB and would be staged as if it were a language model.
  if (buffer.length < 100_000) throw new Error(`${LANG_FILE} is only ${buffer.length} bytes — download failed`);
  writeFileSync(langTarget, buffer);
  copied++;
  process.stdout.write(`${(buffer.length / 1024 / 1024).toFixed(1)} MB\n`);
}
bytes += sizeOf(langTarget);

// The app asks for one base path and derives the rest; keep it in sync with the
// folder this script just filled so a version bump is a one-line change.
const manifest = {
  version: VERSION,
  coreVersion: corePkg.version,
  lang: LANG,
  files: ['worker.min.js', ...CORES, LANG_FILE],
};
writeFileSync(
  path.join(OUT_DIR, 'manifest.json'),
  `/* Generated by scripts/sync-ocr.mjs — do not edit by hand. */\n${JSON.stringify(manifest, null, 2)}\n`,
  'utf8',
);

if (copied) console.log(`   [ocr] staged ${copied} file(s) for tesseract.js ${VERSION}`);
console.log(`   [ocr] ${(bytes / 1024 / 1024).toFixed(1)} MB of OCR assets ready at /vendor/tesseract/${VERSION}/`);
